/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import openai.javasdk.utils.HTTPClient;
import openai.javasdk.utils.HTTPRequest;
import openai.javasdk.utils.JSON;
import openai.javasdk.utils.SerializedBody;
import org.apache.http.NameValuePair;

/**
 * The OpenAI REST API
 */
public class OpenAI {
	
	private HTTPClient _defaultClient;
	private HTTPClient _securityClient;
	private String _serverUrl;
	private String _language;
	private String _sdkVersion;
	private String _genVersion;

	public OpenAI(HTTPClient defaultClient, HTTPClient securityClient, String serverUrl, String language, String sdkVersion, String genVersion) {
		this._defaultClient = defaultClient;
		this._securityClient = securityClient;
		this._serverUrl = serverUrl;
		this._language = language;
		this._sdkVersion = sdkVersion;
		this._genVersion = genVersion;
	}

    public openai.javasdk.models.operations.CancelFineTuneResponse cancelFineTune(openai.javasdk.models.operations.CancelFineTuneRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.CancelFineTuneRequest.class, baseUrl, "/fine-tunes/{fine_tune_id}/cancel", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CancelFineTuneResponse res = new openai.javasdk.models.operations.CancelFineTuneResponse(contentType, httpRes.statusCode()) {{
            fineTune = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.FineTune out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.FineTune.class);
                res.fineTune = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateAnswerResponse createAnswer(openai.javasdk.models.shared.CreateAnswerRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/answers");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateAnswerResponse res = new openai.javasdk.models.operations.CreateAnswerResponse(contentType, httpRes.statusCode()) {{
            createAnswerResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateAnswerResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateAnswerResponse.class);
                res.createAnswerResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateChatCompletionResponse createChatCompletion(openai.javasdk.models.shared.CreateChatCompletionRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/chat/completions");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateChatCompletionResponse res = new openai.javasdk.models.operations.CreateChatCompletionResponse(contentType, httpRes.statusCode()) {{
            createChatCompletionResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateChatCompletionResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateChatCompletionResponse.class);
                res.createChatCompletionResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateClassificationResponse createClassification(openai.javasdk.models.shared.CreateClassificationRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/classifications");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateClassificationResponse res = new openai.javasdk.models.operations.CreateClassificationResponse(contentType, httpRes.statusCode()) {{
            createClassificationResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateClassificationResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateClassificationResponse.class);
                res.createClassificationResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateCompletionResponse createCompletion(openai.javasdk.models.shared.CreateCompletionRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/completions");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateCompletionResponse res = new openai.javasdk.models.operations.CreateCompletionResponse(contentType, httpRes.statusCode()) {{
            createCompletionResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateCompletionResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateCompletionResponse.class);
                res.createCompletionResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateEditResponse createEdit(openai.javasdk.models.shared.CreateEditRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/edits");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateEditResponse res = new openai.javasdk.models.operations.CreateEditResponse(contentType, httpRes.statusCode()) {{
            createEditResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateEditResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateEditResponse.class);
                res.createEditResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateEmbeddingResponse createEmbedding(openai.javasdk.models.shared.CreateEmbeddingRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/embeddings");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateEmbeddingResponse res = new openai.javasdk.models.operations.CreateEmbeddingResponse(contentType, httpRes.statusCode()) {{
            createEmbeddingResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateEmbeddingResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateEmbeddingResponse.class);
                res.createEmbeddingResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateFileResponse createFile(openai.javasdk.models.shared.CreateFileRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/files");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "multipart");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateFileResponse res = new openai.javasdk.models.operations.CreateFileResponse(contentType, httpRes.statusCode()) {{
            openAIFile = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.OpenAIFile out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.OpenAIFile.class);
                res.openAIFile = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateFineTuneResponse createFineTune(openai.javasdk.models.shared.CreateFineTuneRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/fine-tunes");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateFineTuneResponse res = new openai.javasdk.models.operations.CreateFineTuneResponse(contentType, httpRes.statusCode()) {{
            fineTune = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.FineTune out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.FineTune.class);
                res.fineTune = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateImageResponse createImage(openai.javasdk.models.shared.CreateImageRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/images/generations");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateImageResponse res = new openai.javasdk.models.operations.CreateImageResponse(contentType, httpRes.statusCode()) {{
            imagesResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.ImagesResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.ImagesResponse.class);
                res.imagesResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateImageEditResponse createImageEdit(openai.javasdk.models.shared.CreateImageEditRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/images/edits");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "multipart");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateImageEditResponse res = new openai.javasdk.models.operations.CreateImageEditResponse(contentType, httpRes.statusCode()) {{
            imagesResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.ImagesResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.ImagesResponse.class);
                res.imagesResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateImageVariationResponse createImageVariation(openai.javasdk.models.shared.CreateImageVariationRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/images/variations");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "multipart");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateImageVariationResponse res = new openai.javasdk.models.operations.CreateImageVariationResponse(contentType, httpRes.statusCode()) {{
            imagesResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.ImagesResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.ImagesResponse.class);
                res.imagesResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateModerationResponse createModeration(openai.javasdk.models.shared.CreateModerationRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/moderations");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateModerationResponse res = new openai.javasdk.models.operations.CreateModerationResponse(contentType, httpRes.statusCode()) {{
            createModerationResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateModerationResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateModerationResponse.class);
                res.createModerationResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateSearchResponse createSearch(openai.javasdk.models.operations.CreateSearchRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.CreateSearchRequest.class, baseUrl, "/engines/{engine_id}/search", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "createSearchRequest", "json");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateSearchResponse res = new openai.javasdk.models.operations.CreateSearchResponse(contentType, httpRes.statusCode()) {{
            createSearchResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateSearchResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateSearchResponse.class);
                res.createSearchResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateTranscriptionResponse createTranscription(openai.javasdk.models.shared.CreateTranscriptionRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/audio/transcriptions");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "multipart");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateTranscriptionResponse res = new openai.javasdk.models.operations.CreateTranscriptionResponse(contentType, httpRes.statusCode()) {{
            createTranscriptionResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateTranscriptionResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateTranscriptionResponse.class);
                res.createTranscriptionResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.CreateTranslationResponse createTranslation(openai.javasdk.models.shared.CreateTranslationRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/audio/translations");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("POST");
        req.setURL(url);
        SerializedBody serializedRequestBody = openai.javasdk.utils.Utils.serializeRequestBody(request, "request", "multipart");
        if (serializedRequestBody == null) {
            throw new Exception("Request body is required");
        }
        req.setBody(serializedRequestBody);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.CreateTranslationResponse res = new openai.javasdk.models.operations.CreateTranslationResponse(contentType, httpRes.statusCode()) {{
            createTranslationResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.CreateTranslationResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.CreateTranslationResponse.class);
                res.createTranslationResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.DeleteFileResponse deleteFile(openai.javasdk.models.operations.DeleteFileRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.DeleteFileRequest.class, baseUrl, "/files/{file_id}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("DELETE");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.DeleteFileResponse res = new openai.javasdk.models.operations.DeleteFileResponse(contentType, httpRes.statusCode()) {{
            deleteFileResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.DeleteFileResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.DeleteFileResponse.class);
                res.deleteFileResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.DeleteModelResponse deleteModel(openai.javasdk.models.operations.DeleteModelRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.DeleteModelRequest.class, baseUrl, "/models/{model}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("DELETE");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.DeleteModelResponse res = new openai.javasdk.models.operations.DeleteModelResponse(contentType, httpRes.statusCode()) {{
            deleteModelResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.DeleteModelResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.DeleteModelResponse.class);
                res.deleteModelResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.DownloadFileResponse downloadFile(openai.javasdk.models.operations.DownloadFileRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.DownloadFileRequest.class, baseUrl, "/files/{file_id}/content", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.DownloadFileResponse res = new openai.javasdk.models.operations.DownloadFileResponse(contentType, httpRes.statusCode()) {{
            downloadFile200ApplicationJSONString = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                String out = new String(httpRes.body(), StandardCharsets.UTF_8);
                res.downloadFile200ApplicationJSONString = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.ListEnginesResponse listEngines() throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/engines");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.ListEnginesResponse res = new openai.javasdk.models.operations.ListEnginesResponse(contentType, httpRes.statusCode()) {{
            listEnginesResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.ListEnginesResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.ListEnginesResponse.class);
                res.listEnginesResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.ListFilesResponse listFiles() throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/files");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.ListFilesResponse res = new openai.javasdk.models.operations.ListFilesResponse(contentType, httpRes.statusCode()) {{
            listFilesResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.ListFilesResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.ListFilesResponse.class);
                res.listFilesResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.ListFineTuneEventsResponse listFineTuneEvents(openai.javasdk.models.operations.ListFineTuneEventsRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.ListFineTuneEventsRequest.class, baseUrl, "/fine-tunes/{fine_tune_id}/events", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        java.util.List<NameValuePair> queryParams = openai.javasdk.utils.Utils.getQueryParams(openai.javasdk.models.operations.ListFineTuneEventsRequest.class, request, null);
        if (queryParams != null) {
            for (NameValuePair queryParam : queryParams) {
                req.addQueryParam(queryParam);
            }
        }
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.ListFineTuneEventsResponse res = new openai.javasdk.models.operations.ListFineTuneEventsResponse(contentType, httpRes.statusCode()) {{
            listFineTuneEventsResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.ListFineTuneEventsResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.ListFineTuneEventsResponse.class);
                res.listFineTuneEventsResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.ListFineTunesResponse listFineTunes() throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/fine-tunes");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.ListFineTunesResponse res = new openai.javasdk.models.operations.ListFineTunesResponse(contentType, httpRes.statusCode()) {{
            listFineTunesResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.ListFineTunesResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.ListFineTunesResponse.class);
                res.listFineTunesResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.ListModelsResponse listModels() throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(baseUrl, "/models");
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.ListModelsResponse res = new openai.javasdk.models.operations.ListModelsResponse(contentType, httpRes.statusCode()) {{
            listModelsResponse = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.ListModelsResponse out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.ListModelsResponse.class);
                res.listModelsResponse = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.RetrieveEngineResponse retrieveEngine(openai.javasdk.models.operations.RetrieveEngineRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.RetrieveEngineRequest.class, baseUrl, "/engines/{engine_id}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.RetrieveEngineResponse res = new openai.javasdk.models.operations.RetrieveEngineResponse(contentType, httpRes.statusCode()) {{
            engine = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.Engine out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.Engine.class);
                res.engine = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.RetrieveFileResponse retrieveFile(openai.javasdk.models.operations.RetrieveFileRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.RetrieveFileRequest.class, baseUrl, "/files/{file_id}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.RetrieveFileResponse res = new openai.javasdk.models.operations.RetrieveFileResponse(contentType, httpRes.statusCode()) {{
            openAIFile = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.OpenAIFile out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.OpenAIFile.class);
                res.openAIFile = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.RetrieveFineTuneResponse retrieveFineTune(openai.javasdk.models.operations.RetrieveFineTuneRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.RetrieveFineTuneRequest.class, baseUrl, "/fine-tunes/{fine_tune_id}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.RetrieveFineTuneResponse res = new openai.javasdk.models.operations.RetrieveFineTuneResponse(contentType, httpRes.statusCode()) {{
            fineTune = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.FineTune out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.FineTune.class);
                res.fineTune = out;
            }
        }

        return res;
    }

    public openai.javasdk.models.operations.RetrieveModelResponse retrieveModel(openai.javasdk.models.operations.RetrieveModelRequest request) throws Exception {
        String baseUrl = this._serverUrl;
        String url = openai.javasdk.utils.Utils.generateURL(openai.javasdk.models.operations.RetrieveModelRequest.class, baseUrl, "/models/{model}", request, null);
        
        HTTPRequest req = new HTTPRequest();
        req.setMethod("GET");
        req.setURL(url);
        
        
        HTTPClient client = this._defaultClient;
        HttpResponse<byte[]> httpRes = client.send(req);

        String contentType = httpRes.headers().firstValue("Content-Type").orElse("application/octet-stream");

        openai.javasdk.models.operations.RetrieveModelResponse res = new openai.javasdk.models.operations.RetrieveModelResponse(contentType, httpRes.statusCode()) {{
            model = null;
        }};
        res.rawResponse = httpRes;
        
        if (httpRes.statusCode() == 200) {
            if (openai.javasdk.utils.Utils.matchContentType(contentType, "application/json")) {
                ObjectMapper mapper = JSON.getMapper();
                openai.javasdk.models.shared.Model out = mapper.readValue(new String(httpRes.body(), StandardCharsets.UTF_8), openai.javasdk.models.shared.Model.class);
                res.model = out;
            }
        }

        return res;
    }
}