/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.operations;

import java.net.http.HttpResponse;

public class CreateImageEditResponse {
    
    public String contentType;
    public CreateImageEditResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public openai.javasdk.models.shared.ImagesResponse imagesResponse;
    public CreateImageEditResponse withImagesResponse(openai.javasdk.models.shared.ImagesResponse imagesResponse) {
        this.imagesResponse = imagesResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public CreateImageEditResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public CreateImageEditResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
