/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.operations;

import java.net.http.HttpResponse;

public class DeleteModelResponse {
    
    public String contentType;
    public DeleteModelResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public openai.javasdk.models.shared.DeleteModelResponse deleteModelResponse;
    public DeleteModelResponse withDeleteModelResponse(openai.javasdk.models.shared.DeleteModelResponse deleteModelResponse) {
        this.deleteModelResponse = deleteModelResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public DeleteModelResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public DeleteModelResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
