/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.operations;

import java.net.http.HttpResponse;

public class DeleteFileResponse {
    
    public String contentType;
    public DeleteFileResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public openai.javasdk.models.shared.DeleteFileResponse deleteFileResponse;
    public DeleteFileResponse withDeleteFileResponse(openai.javasdk.models.shared.DeleteFileResponse deleteFileResponse) {
        this.deleteFileResponse = deleteFileResponse;
        return this;
    }
    
    
    public Integer statusCode;
    public DeleteFileResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public DeleteFileResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
}
