/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.operations;

import openai.javasdk.utils.SpeakeasyMetadata;

public class RetrieveFineTuneRequest {
    /**
     * The ID of the fine-tune job
     * 
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=fine_tune_id")public String fineTuneId;
    public RetrieveFineTuneRequest withFineTuneId(String fineTuneId) {
        this.fineTuneId = fineTuneId;
        return this;
    }
    
}
