/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import openai.javasdk.utils.SpeakeasyMetadata;

public class RetrieveModelRequest {
    /**
     * The ID of the model to use for this request
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=model")
    public String model;
    public RetrieveModelRequest withModel(String model) {
        this.model = model;
        return this;
    }
    
    public RetrieveModelRequest(@JsonProperty("model") String model) {
        this.model = model;
  }
}
