/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ChatCompletionRequestMessageFunctionCall - The name and arguments of a function that should be called, as generated by the model.
 */

public class ChatCompletionRequestMessageFunctionCall {
    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    @JsonProperty("arguments")
    public String arguments;

    public ChatCompletionRequestMessageFunctionCall withArguments(String arguments) {
        this.arguments = arguments;
        return this;
    }
    
    /**
     * The name of the function to call.
     */
    @JsonProperty("name")
    public String name;

    public ChatCompletionRequestMessageFunctionCall withName(String name) {
        this.name = name;
        return this;
    }
    
    public ChatCompletionRequestMessageFunctionCall(@JsonProperty("arguments") String arguments, @JsonProperty("name") String name) {
        this.arguments = arguments;
        this.name = name;
  }
}
