/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChatCompletionResponseMessageRole - The role of the author of this message.
 */
public enum ChatCompletionResponseMessageRole {
    SYSTEM("system"),
    USER("user"),
    ASSISTANT("assistant"),
    FUNCTION("function");

    @JsonValue
    public final String value;

    private ChatCompletionResponseMessageRole(String value) {
        this.value = value;
    }
}
