/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChatCompletionRequestMessageRole - The role of the messages author. One of `system`, `user`, `assistant`, or `function`.
 */
public enum ChatCompletionRequestMessageRole {
    SYSTEM("system"),
    USER("user"),
    ASSISTANT("assistant"),
    FUNCTION("function");

    @JsonValue
    public final String value;

    private ChatCompletionRequestMessageRole(String value) {
        this.value = value;
    }
}
