/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class ChatCompletionRequestMessage {
    /**
     * The contents of the message. `content` is required for all messages, and may be null for assistant messages with function calls.
     */
    @JsonProperty("content")
    public String content;

    public ChatCompletionRequestMessage withContent(String content) {
        this.content = content;
        return this;
    }
    
    /**
     * The name and arguments of a function that should be called, as generated by the model.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("function_call")
    public ChatCompletionRequestMessageFunctionCall functionCall;

    public ChatCompletionRequestMessage withFunctionCall(ChatCompletionRequestMessageFunctionCall functionCall) {
        this.functionCall = functionCall;
        return this;
    }
    
    /**
     * The name of the author of this message. `name` is required if role is `function`, and it should be the name of the function whose response is in the `content`. May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public ChatCompletionRequestMessage withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The role of the messages author. One of `system`, `user`, `assistant`, or `function`.
     */
    @JsonProperty("role")
    public ChatCompletionRequestMessageRole role;

    public ChatCompletionRequestMessage withRole(ChatCompletionRequestMessageRole role) {
        this.role = role;
        return this;
    }
    
    public ChatCompletionRequestMessage(@JsonProperty("content") String content, @JsonProperty("role") ChatCompletionRequestMessageRole role) {
        this.content = content;
        this.role = role;
  }
}
