/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ChatCompletionResponseMessage {
    /**
     * The contents of the message
     */
    @JsonProperty("content")
    public String content;
    public ChatCompletionResponseMessage withContent(String content) {
        this.content = content;
        return this;
    }
    
    /**
     * The role of the author of this message.
     */
    @JsonProperty("role")
    public ChatCompletionResponseMessageRoleEnum role;
    public ChatCompletionResponseMessage withRole(ChatCompletionResponseMessageRoleEnum role) {
        this.role = role;
        return this;
    }
    
}
