/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ChatCompletionRequestMessage {
    /**
     * The contents of the message
     */
    @JsonProperty("content")
    public String content;
    public ChatCompletionRequestMessage withContent(String content) {
        this.content = content;
        return this;
    }
    
    /**
     * The name of the user in a multi-user chat
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;
    public ChatCompletionRequestMessage withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The role of the author of this message.
     */
    @JsonProperty("role")
    public ChatCompletionRequestMessageRoleEnum role;
    public ChatCompletionRequestMessage withRole(ChatCompletionRequestMessageRoleEnum role) {
        this.role = role;
        return this;
    }
    
    public ChatCompletionRequestMessage(@JsonProperty("content") String content, @JsonProperty("role") ChatCompletionRequestMessageRoleEnum role) {
        this.content = content;
        this.role = role;
  }
}
