/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ChatCompletionRequestMessageRoleEnum - The role of the author of this message.
 */
public enum ChatCompletionRequestMessageRoleEnum {
    SYSTEM("system"),
    USER("user"),
    ASSISTANT("assistant");

    @JsonValue
    public final String value;

    private ChatCompletionRequestMessageRoleEnum(String value) {
        this.value = value;
    }
}
