/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ChatCompletionResponseMessage - A chat completion message generated by the model.
 */

public class ChatCompletionResponseMessage {
    /**
     * The contents of the message.
     */
    @JsonProperty("content")
    public String content;

    public ChatCompletionResponseMessage withContent(String content) {
        this.content = content;
        return this;
    }
    
    /**
     * The name and arguments of a function that should be called, as generated by the model.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("function_call")
    public ChatCompletionResponseMessageFunctionCall functionCall;

    public ChatCompletionResponseMessage withFunctionCall(ChatCompletionResponseMessageFunctionCall functionCall) {
        this.functionCall = functionCall;
        return this;
    }
    
    /**
     * The role of the author of this message.
     */
    @JsonProperty("role")
    public ChatCompletionResponseMessageRole role;

    public ChatCompletionResponseMessage withRole(ChatCompletionResponseMessageRole role) {
        this.role = role;
        return this;
    }
    
    public ChatCompletionResponseMessage(@JsonProperty("content") String content, @JsonProperty("role") ChatCompletionResponseMessageRole role) {
        this.content = content;
        this.role = role;
  }
}
