/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateCompletionResponseChoices {
    @JsonProperty("finish_reason")
    public String finishReason;

    public CreateCompletionResponseChoices withFinishReason(String finishReason) {
        this.finishReason = finishReason;
        return this;
    }
    
    @JsonProperty("index")
    public Long index;

    public CreateCompletionResponseChoices withIndex(Long index) {
        this.index = index;
        return this;
    }
    
    @JsonProperty("logprobs")
    public CreateCompletionResponseChoicesLogprobs logprobs;

    public CreateCompletionResponseChoices withLogprobs(CreateCompletionResponseChoicesLogprobs logprobs) {
        this.logprobs = logprobs;
        return this;
    }
    
    @JsonProperty("text")
    public String text;

    public CreateCompletionResponseChoices withText(String text) {
        this.text = text;
        return this;
    }
    
    public CreateCompletionResponseChoices(@JsonProperty("finish_reason") String finishReason, @JsonProperty("index") Long index, @JsonProperty("logprobs") CreateCompletionResponseChoicesLogprobs logprobs, @JsonProperty("text") String text) {
        this.finishReason = finishReason;
        this.index = index;
        this.logprobs = logprobs;
        this.text = text;
  }
}
