/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateChatCompletionResponseChoicesFinishReason - The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
 * `length` if the maximum number of tokens specified in the request was reached, or `function_call` if the model called a function.
 * 
 */
public enum CreateChatCompletionResponseChoicesFinishReason {
    STOP("stop"),
    LENGTH("length"),
    FUNCTION_CALL("function_call");

    @JsonValue
    public final String value;

    private CreateChatCompletionResponseChoicesFinishReason(String value) {
        this.value = value;
    }
}
