/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateTranscriptionRequestModel2 - ID of the model to use. Only `whisper-1` is currently available.
 * 
 */
public enum CreateTranscriptionRequestModel2 {
    WHISPER1("whisper-1");

    @JsonValue
    public final String value;

    private CreateTranscriptionRequestModel2(String value) {
        this.value = value;
    }
}
