/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateCompletionResponse - Represents a completion response from the API. Note: both the streamed and non-streamed response objects share the same shape (unlike the chat endpoint).
 * 
 */

public class CreateCompletionResponse {
    /**
     * The list of completion choices the model generated for the input prompt.
     */
    @JsonProperty("choices")
    public CreateCompletionResponseChoices[] choices;

    public CreateCompletionResponse withChoices(CreateCompletionResponseChoices[] choices) {
        this.choices = choices;
        return this;
    }
    
    /**
     * The Unix timestamp of when the completion was created.
     */
    @JsonProperty("created")
    public Long created;

    public CreateCompletionResponse withCreated(Long created) {
        this.created = created;
        return this;
    }
    
    /**
     * A unique identifier for the completion.
     */
    @JsonProperty("id")
    public String id;

    public CreateCompletionResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The model used for completion.
     */
    @JsonProperty("model")
    public String model;

    public CreateCompletionResponse withModel(String model) {
        this.model = model;
        return this;
    }
    
    /**
     * The object type, which is always "text_completion"
     */
    @JsonProperty("object")
    public String object;

    public CreateCompletionResponse withObject(String object) {
        this.object = object;
        return this;
    }
    
    /**
     * Usage statistics for the completion request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("usage")
    public CompletionUsage usage;

    public CreateCompletionResponse withUsage(CompletionUsage usage) {
        this.usage = usage;
        return this;
    }
    
    public CreateCompletionResponse(@JsonProperty("choices") CreateCompletionResponseChoices[] choices, @JsonProperty("created") Long created, @JsonProperty("id") String id, @JsonProperty("model") String model, @JsonProperty("object") String object) {
        this.choices = choices;
        this.created = created;
        this.id = id;
        this.model = model;
        this.object = object;
  }
}
