/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import openai.javasdk.utils.SpeakeasyMetadata;


public class CreateImageEditRequest2 {
    /**
     * The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask.
     */
    @SpeakeasyMetadata("multipartForm:file")
    public CreateImageEditRequestImage image;

    public CreateImageEditRequest2 withImage(CreateImageEditRequestImage image) {
        this.image = image;
        return this;
    }
    
    /**
     * An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as `image`.
     */
    @SpeakeasyMetadata("multipartForm:file")
    public CreateImageEditRequestMask mask;

    public CreateImageEditRequest2 withMask(CreateImageEditRequestMask mask) {
        this.mask = mask;
        return this;
    }
    
    /**
     * The number of images to generate. Must be between 1 and 10.
     */
    @SpeakeasyMetadata("multipartForm:name=n")
    public Long n;

    public CreateImageEditRequest2 withN(Long n) {
        this.n = n;
        return this;
    }
    
    /**
     * A text description of the desired image(s). The maximum length is 1000 characters.
     */
    @SpeakeasyMetadata("multipartForm:name=prompt")
    public String prompt;

    public CreateImageEditRequest2 withPrompt(String prompt) {
        this.prompt = prompt;
        return this;
    }
    
    /**
     * The format in which the generated images are returned. Must be one of `url` or `b64_json`.
     */
    @SpeakeasyMetadata("multipartForm:name=response_format")
    public CreateImageEditRequestResponseFormat responseFormat;

    public CreateImageEditRequest2 withResponseFormat(CreateImageEditRequestResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }
    
    /**
     * The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
     */
    @SpeakeasyMetadata("multipartForm:name=size")
    public CreateImageEditRequestSize size;

    public CreateImageEditRequest2 withSize(CreateImageEditRequestSize size) {
        this.size = size;
        return this;
    }
    
    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).
     * 
     */
    @SpeakeasyMetadata("multipartForm:name=user")
    public String user;

    public CreateImageEditRequest2 withUser(String user) {
        this.user = user;
        return this;
    }
    
    public CreateImageEditRequest2(@JsonProperty("image") CreateImageEditRequestImage image, @JsonProperty("prompt") String prompt) {
        this.image = image;
        this.prompt = prompt;
  }
}
