/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateCompletionRequestModel2 - ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them.
 * 
 */
public enum CreateCompletionRequestModel2 {
    TEXT_DAVINCI003("text-davinci-003"),
    TEXT_DAVINCI002("text-davinci-002"),
    TEXT_DAVINCI001("text-davinci-001"),
    CODE_DAVINCI002("code-davinci-002"),
    TEXT_CURIE001("text-curie-001"),
    TEXT_BABBAGE001("text-babbage-001"),
    TEXT_ADA001("text-ada-001");

    @JsonValue
    public final String value;

    private CreateCompletionRequestModel2(String value) {
        this.value = value;
    }
}
