/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum CreateEditResponseChoicesFinishReason {
    STOP("stop"),
    LENGTH("length");

    @JsonValue
    public final String value;

    private CreateEditResponseChoicesFinishReason(String value) {
        this.value = value;
    }
}
