/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateModerationResponseResultsCategories - A list of the categories, and whether they are flagged or not.
 */

public class CreateModerationResponseResultsCategories {
    /**
     * Whether the content was flagged as 'hate'.
     */
    @JsonProperty("hate")
    public Boolean hate;

    public CreateModerationResponseResultsCategories withHate(Boolean hate) {
        this.hate = hate;
        return this;
    }
    
    /**
     * Whether the content was flagged as 'hate/threatening'.
     */
    @JsonProperty("hate/threatening")
    public Boolean hateThreatening;

    public CreateModerationResponseResultsCategories withHateThreatening(Boolean hateThreatening) {
        this.hateThreatening = hateThreatening;
        return this;
    }
    
    /**
     * Whether the content was flagged as 'self-harm'.
     */
    @JsonProperty("self-harm")
    public Boolean selfHarm;

    public CreateModerationResponseResultsCategories withSelfHarm(Boolean selfHarm) {
        this.selfHarm = selfHarm;
        return this;
    }
    
    /**
     * Whether the content was flagged as 'sexual'.
     */
    @JsonProperty("sexual")
    public Boolean sexual;

    public CreateModerationResponseResultsCategories withSexual(Boolean sexual) {
        this.sexual = sexual;
        return this;
    }
    
    /**
     * Whether the content was flagged as 'sexual/minors'.
     */
    @JsonProperty("sexual/minors")
    public Boolean sexualMinors;

    public CreateModerationResponseResultsCategories withSexualMinors(Boolean sexualMinors) {
        this.sexualMinors = sexualMinors;
        return this;
    }
    
    /**
     * Whether the content was flagged as 'violence'.
     */
    @JsonProperty("violence")
    public Boolean violence;

    public CreateModerationResponseResultsCategories withViolence(Boolean violence) {
        this.violence = violence;
        return this;
    }
    
    /**
     * Whether the content was flagged as 'violence/graphic'.
     */
    @JsonProperty("violence/graphic")
    public Boolean violenceGraphic;

    public CreateModerationResponseResultsCategories withViolenceGraphic(Boolean violenceGraphic) {
        this.violenceGraphic = violenceGraphic;
        return this;
    }
    
    public CreateModerationResponseResultsCategories(@JsonProperty("hate") Boolean hate, @JsonProperty("hate/threatening") Boolean hateThreatening, @JsonProperty("self-harm") Boolean selfHarm, @JsonProperty("sexual") Boolean sexual, @JsonProperty("sexual/minors") Boolean sexualMinors, @JsonProperty("violence") Boolean violence, @JsonProperty("violence/graphic") Boolean violenceGraphic) {
        this.hate = hate;
        this.hateThreatening = hateThreatening;
        this.selfHarm = selfHarm;
        this.sexual = sexual;
        this.sexualMinors = sexualMinors;
        this.violence = violence;
        this.violenceGraphic = violenceGraphic;
  }
}
