/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateModerationResponseResultsCategoryScores - A list of the categories along with their scores as predicted by model.
 */

public class CreateModerationResponseResultsCategoryScores {
    /**
     * The score for the category 'hate'.
     */
    @JsonProperty("hate")
    public Double hate;

    public CreateModerationResponseResultsCategoryScores withHate(Double hate) {
        this.hate = hate;
        return this;
    }
    
    /**
     * The score for the category 'hate/threatening'.
     */
    @JsonProperty("hate/threatening")
    public Double hateThreatening;

    public CreateModerationResponseResultsCategoryScores withHateThreatening(Double hateThreatening) {
        this.hateThreatening = hateThreatening;
        return this;
    }
    
    /**
     * The score for the category 'self-harm'.
     */
    @JsonProperty("self-harm")
    public Double selfHarm;

    public CreateModerationResponseResultsCategoryScores withSelfHarm(Double selfHarm) {
        this.selfHarm = selfHarm;
        return this;
    }
    
    /**
     * The score for the category 'sexual'.
     */
    @JsonProperty("sexual")
    public Double sexual;

    public CreateModerationResponseResultsCategoryScores withSexual(Double sexual) {
        this.sexual = sexual;
        return this;
    }
    
    /**
     * The score for the category 'sexual/minors'.
     */
    @JsonProperty("sexual/minors")
    public Double sexualMinors;

    public CreateModerationResponseResultsCategoryScores withSexualMinors(Double sexualMinors) {
        this.sexualMinors = sexualMinors;
        return this;
    }
    
    /**
     * The score for the category 'violence'.
     */
    @JsonProperty("violence")
    public Double violence;

    public CreateModerationResponseResultsCategoryScores withViolence(Double violence) {
        this.violence = violence;
        return this;
    }
    
    /**
     * The score for the category 'violence/graphic'.
     */
    @JsonProperty("violence/graphic")
    public Double violenceGraphic;

    public CreateModerationResponseResultsCategoryScores withViolenceGraphic(Double violenceGraphic) {
        this.violenceGraphic = violenceGraphic;
        return this;
    }
    
    public CreateModerationResponseResultsCategoryScores(@JsonProperty("hate") Double hate, @JsonProperty("hate/threatening") Double hateThreatening, @JsonProperty("self-harm") Double selfHarm, @JsonProperty("sexual") Double sexual, @JsonProperty("sexual/minors") Double sexualMinors, @JsonProperty("violence") Double violence, @JsonProperty("violence/graphic") Double violenceGraphic) {
        this.hate = hate;
        this.hateThreatening = hateThreatening;
        this.selfHarm = selfHarm;
        this.sexual = sexual;
        this.sexualMinors = sexualMinors;
        this.violence = violence;
        this.violenceGraphic = violenceGraphic;
  }
}
