/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import openai.javasdk.utils.SpeakeasyMetadata;


public class CreateImageVariationRequest {
    /**
     * The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square.
     */
    @SpeakeasyMetadata("multipartForm:file")
    public CreateImageVariationRequestImage image;

    public CreateImageVariationRequest withImage(CreateImageVariationRequestImage image) {
        this.image = image;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=n")
    public Object n;

    public CreateImageVariationRequest withN(Object n) {
        this.n = n;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=response_format")
    public Object responseFormat;

    public CreateImageVariationRequest withResponseFormat(Object responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=size")
    public Object size;

    public CreateImageVariationRequest withSize(Object size) {
        this.size = size;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=user")
    public Object user;

    public CreateImageVariationRequest withUser(Object user) {
        this.user = user;
        return this;
    }
    
    public CreateImageVariationRequest(@JsonProperty("image") CreateImageVariationRequestImage image) {
        this.image = image;
  }
}
