/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import openai.javasdk.utils.SpeakeasyMetadata;


public class CreateFileRequestFile {
    @SpeakeasyMetadata("multipartForm:content")
    public byte[] content;

    public CreateFileRequestFile withContent(byte[] content) {
        this.content = content;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=file")
    public String file;

    public CreateFileRequestFile withFile(String file) {
        this.file = file;
        return this;
    }
    
    public CreateFileRequestFile(@JsonProperty("content") byte[] content, @JsonProperty("file") String file) {
        this.content = content;
        this.file = file;
  }
}
