/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateEmbeddingRequestModel2 - ID of the model to use. You can use the [List models](/docs/api-reference/models/list) API to see all of your available models, or see our [Model overview](/docs/models/overview) for descriptions of them.
 * 
 */
public enum CreateEmbeddingRequestModel2 {
    TEXT_EMBEDDING_ADA002("text-embedding-ada-002");

    @JsonValue
    public final String value;

    private CreateEmbeddingRequestModel2(String value) {
        this.value = value;
    }
}
