/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateModerationResponse - Represents policy compliance report by OpenAI's content moderation model against a given input.
 */

public class CreateModerationResponse {
    /**
     * The unique identifier for the moderation request.
     */
    @JsonProperty("id")
    public String id;

    public CreateModerationResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The model used to generate the moderation results.
     */
    @JsonProperty("model")
    public String model;

    public CreateModerationResponse withModel(String model) {
        this.model = model;
        return this;
    }
    
    /**
     * A list of moderation objects.
     */
    @JsonProperty("results")
    public CreateModerationResponseResults[] results;

    public CreateModerationResponse withResults(CreateModerationResponseResults[] results) {
        this.results = results;
        return this;
    }
    
    public CreateModerationResponse(@JsonProperty("id") String id, @JsonProperty("model") String model, @JsonProperty("results") CreateModerationResponseResults[] results) {
        this.id = id;
        this.model = model;
        this.results = results;
  }
}
