/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateEditResponseChoicesFinishReason - The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
 * or `length` if the maximum number of tokens specified in the request was reached.
 * 
 */
public enum CreateEditResponseChoicesFinishReason {
    STOP("stop"),
    LENGTH("length");

    @JsonValue
    public final String value;

    private CreateEditResponseChoicesFinishReason(String value) {
        this.value = value;
    }
}
