/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import openai.javasdk.utils.SpeakeasyMetadata;

public class CreateImageEditRequestImage {
    @SpeakeasyMetadata("multipartForm:content")
    public byte[] content;
    public CreateImageEditRequestImage withContent(byte[] content) {
        this.content = content;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=image")
    public String image;
    public CreateImageEditRequestImage withImage(String image) {
        this.image = image;
        return this;
    }
    

    public CreateImageEditRequestImage(@JsonProperty("content") byte[] content, @JsonProperty("image") String image) {
    this.content = content;
this.image = image;
  }
}
