/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateEmbeddingRequestModel2 - model_description
 */
public enum CreateEmbeddingRequestModel2 {
    TEXT_EMBEDDING_ADA002("text-embedding-ada-002");

    @JsonValue
    public final String value;

    private CreateEmbeddingRequestModel2(String value) {
        this.value = value;
    }
}
