/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum CreateChatCompletionResponseChoicesFinishReason {
    STOP("stop"),
    LENGTH("length"),
    FUNCTION_CALL("function_call");

    @JsonValue
    public final String value;

    private CreateChatCompletionResponseChoicesFinishReason(String value) {
        this.value = value;
    }
}
