/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateEditResponse - OK
 */

public class CreateEditResponse {
    /**
     * A list of edit choices. Can be more than one if `n` is greater than 1.
     */
    @JsonProperty("choices")
    public CreateEditResponseChoices[] choices;

    public CreateEditResponse withChoices(CreateEditResponseChoices[] choices) {
        this.choices = choices;
        return this;
    }
    
    /**
     * A unix timestamp of when the edit was created.
     */
    @JsonProperty("created")
    public Long created;

    public CreateEditResponse withCreated(Long created) {
        this.created = created;
        return this;
    }
    
    /**
     * The object type, which is always `edit`.
     */
    @JsonProperty("object")
    public String object;

    public CreateEditResponse withObject(String object) {
        this.object = object;
        return this;
    }
    
    /**
     * Usage statistics for the completion request.
     */
    @JsonProperty("usage")
    public CompletionUsage usage;

    public CreateEditResponse withUsage(CompletionUsage usage) {
        this.usage = usage;
        return this;
    }
    
    public CreateEditResponse(@JsonProperty("choices") CreateEditResponseChoices[] choices, @JsonProperty("created") Long created, @JsonProperty("object") String object, @JsonProperty("usage") CompletionUsage usage) {
        this.choices = choices;
        this.created = created;
        this.object = object;
        this.usage = usage;
  }
}
