/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateChatCompletionResponseChoices {
    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a natural stop point or a provided stop sequence,
     * `length` if the maximum number of tokens specified in the request was reached, or `function_call` if the model called a function.
     * 
     */
    @JsonProperty("finish_reason")
    public CreateChatCompletionResponseChoicesFinishReason finishReason;

    public CreateChatCompletionResponseChoices withFinishReason(CreateChatCompletionResponseChoicesFinishReason finishReason) {
        this.finishReason = finishReason;
        return this;
    }
    
    /**
     * The index of the choice in the list of choices.
     */
    @JsonProperty("index")
    public Long index;

    public CreateChatCompletionResponseChoices withIndex(Long index) {
        this.index = index;
        return this;
    }
    
    /**
     * A chat completion message generated by the model.
     */
    @JsonProperty("message")
    public ChatCompletionResponseMessage message;

    public CreateChatCompletionResponseChoices withMessage(ChatCompletionResponseMessage message) {
        this.message = message;
        return this;
    }
    
    public CreateChatCompletionResponseChoices(@JsonProperty("finish_reason") CreateChatCompletionResponseChoicesFinishReason finishReason, @JsonProperty("index") Long index, @JsonProperty("message") ChatCompletionResponseMessage message) {
        this.finishReason = finishReason;
        this.index = index;
        this.message = message;
  }
}
