/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import openai.javasdk.utils.SpeakeasyMetadata;

public class CreateFileRequest {
    /**
     * Name of the [JSON Lines](https://jsonlines.readthedocs.io/en/latest/) file to be uploaded.
     * 
     * If the `purpose` is set to "fine-tune", each line is a JSON record with "prompt" and "completion" fields representing your [training examples](/docs/guides/fine-tuning/prepare-training-data).
     * 
     */
    @SpeakeasyMetadata("multipartForm:file")
    public CreateFileRequestFile file;
    public CreateFileRequest withFile(CreateFileRequestFile file) {
        this.file = file;
        return this;
    }
    
    /**
     * The intended purpose of the uploaded documents.
     * 
     * Use "fine-tune" for [Fine-tuning](/docs/api-reference/fine-tunes). This allows us to validate the format of the uploaded file.
     * 
     */
    @SpeakeasyMetadata("multipartForm:name=purpose")
    public String purpose;
    public CreateFileRequest withPurpose(String purpose) {
        this.purpose = purpose;
        return this;
    }
    

    public CreateFileRequest(@JsonProperty("file") CreateFileRequestFile file, @JsonProperty("purpose") String purpose) {
    this.file = file;
this.purpose = purpose;
  }
}
