/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateTranslationResponse - OK
 */
public class CreateTranslationResponse {
    @JsonProperty("text")
    public String text;
    public CreateTranslationResponse withText(String text) {
        this.text = text;
        return this;
    }
    

    public CreateTranslationResponse(@JsonProperty("text") String text) {
    this.text = text;
  }
}
