/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateChatCompletionResponse - Represents a chat completion response returned by model, based on the provided input.
 */

public class CreateChatCompletionResponse {
    /**
     * A list of chat completion choices. Can be more than one if `n` is greater than 1.
     */
    @JsonProperty("choices")
    public CreateChatCompletionResponseChoices[] choices;

    public CreateChatCompletionResponse withChoices(CreateChatCompletionResponseChoices[] choices) {
        this.choices = choices;
        return this;
    }
    
    /**
     * A unix timestamp of when the chat completion was created.
     */
    @JsonProperty("created")
    public Long created;

    public CreateChatCompletionResponse withCreated(Long created) {
        this.created = created;
        return this;
    }
    
    /**
     * A unique identifier for the chat completion.
     */
    @JsonProperty("id")
    public String id;

    public CreateChatCompletionResponse withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The model used for the chat completion.
     */
    @JsonProperty("model")
    public String model;

    public CreateChatCompletionResponse withModel(String model) {
        this.model = model;
        return this;
    }
    
    /**
     * The object type, which is always `chat.completion`.
     */
    @JsonProperty("object")
    public String object;

    public CreateChatCompletionResponse withObject(String object) {
        this.object = object;
        return this;
    }
    
    /**
     * Usage statistics for the completion request.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("usage")
    public CompletionUsage usage;

    public CreateChatCompletionResponse withUsage(CompletionUsage usage) {
        this.usage = usage;
        return this;
    }
    
    public CreateChatCompletionResponse(@JsonProperty("choices") CreateChatCompletionResponseChoices[] choices, @JsonProperty("created") Long created, @JsonProperty("id") String id, @JsonProperty("model") String model, @JsonProperty("object") String object) {
        this.choices = choices;
        this.created = created;
        this.id = id;
        this.model = model;
        this.object = object;
  }
}
