/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateTranslationRequestModel2 - ID of the model to use. Only `whisper-1` is currently available.
 * 
 */
public enum CreateTranslationRequestModel2 {
    WHISPER1("whisper-1");

    @JsonValue
    public final String value;

    private CreateTranslationRequestModel2(String value) {
        this.value = value;
    }
}
