/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import openai.javasdk.utils.SpeakeasyMetadata;


public class CreateImageEditRequest {
    /**
     * The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask.
     */
    @SpeakeasyMetadata("multipartForm:file")
    public CreateImageEditRequestImage image;

    public CreateImageEditRequest withImage(CreateImageEditRequestImage image) {
        this.image = image;
        return this;
    }
    
    /**
     * An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as `image`.
     */
    @SpeakeasyMetadata("multipartForm:file")
    public CreateImageEditRequestMask mask;

    public CreateImageEditRequest withMask(CreateImageEditRequestMask mask) {
        this.mask = mask;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=n")
    public Object n;

    public CreateImageEditRequest withN(Object n) {
        this.n = n;
        return this;
    }
    
    /**
     * A text description of the desired image(s). The maximum length is 1000 characters.
     */
    @SpeakeasyMetadata("multipartForm:name=prompt")
    public String prompt;

    public CreateImageEditRequest withPrompt(String prompt) {
        this.prompt = prompt;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=response_format")
    public Object responseFormat;

    public CreateImageEditRequest withResponseFormat(Object responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=size")
    public Object size;

    public CreateImageEditRequest withSize(Object size) {
        this.size = size;
        return this;
    }
    
    @SpeakeasyMetadata("multipartForm:name=user")
    public Object user;

    public CreateImageEditRequest withUser(Object user) {
        this.user = user;
        return this;
    }
    
    public CreateImageEditRequest(@JsonProperty("image") CreateImageEditRequestImage image, @JsonProperty("prompt") String prompt) {
        this.image = image;
        this.prompt = prompt;
  }
}
