/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateImageVariationRequestSize - The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
 */
public enum CreateImageVariationRequestSize {
    TWO_HUNDRED_AND_FIFTY_SIXX256("256x256"),
    FIVE_HUNDRED_AND_TWELVEX512("512x512"),
    ONE_THOUSAND_AND_TWENTY_FOURX1024("1024x1024");

    @JsonValue
    public final String value;

    private CreateImageVariationRequestSize(String value) {
        this.value = value;
    }
}
