/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateEmbeddingResponse - OK
 */

public class CreateEmbeddingResponse {
    /**
     * The list of embeddings generated by the model.
     */
    @JsonProperty("data")
    public Embedding[] data;

    public CreateEmbeddingResponse withData(Embedding[] data) {
        this.data = data;
        return this;
    }
    
    /**
     * The name of the model used to generate the embedding.
     */
    @JsonProperty("model")
    public String model;

    public CreateEmbeddingResponse withModel(String model) {
        this.model = model;
        return this;
    }
    
    /**
     * The object type, which is always "embedding".
     */
    @JsonProperty("object")
    public String object;

    public CreateEmbeddingResponse withObject(String object) {
        this.object = object;
        return this;
    }
    
    /**
     * The usage information for the request.
     */
    @JsonProperty("usage")
    public CreateEmbeddingResponseUsage usage;

    public CreateEmbeddingResponse withUsage(CreateEmbeddingResponseUsage usage) {
        this.usage = usage;
        return this;
    }
    
    public CreateEmbeddingResponse(@JsonProperty("data") Embedding[] data, @JsonProperty("model") String model, @JsonProperty("object") String object, @JsonProperty("usage") CreateEmbeddingResponseUsage usage) {
        this.data = data;
        this.model = model;
        this.object = object;
        this.usage = usage;
  }
}
