/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateEditRequestModel2 - ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint.
 */
public enum CreateEditRequestModel2 {
    TEXT_DAVINCI_EDIT001("text-davinci-edit-001"),
    CODE_DAVINCI_EDIT001("code-davinci-edit-001");

    @JsonValue
    public final String value;

    private CreateEditRequestModel2(String value) {
        this.value = value;
    }
}
