/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateFineTuneRequestModel2 - The name of the base model to fine-tune. You can select one of "ada",
 * "babbage", "curie", "davinci", or a fine-tuned model created after 2022-04-21.
 * To learn more about these models, see the
 * [Models](https://platform.openai.com/docs/models) documentation.
 * 
 */
public enum CreateFineTuneRequestModel2 {
    ADA("ada"),
    BABBAGE("babbage"),
    CURIE("curie"),
    DAVINCI("davinci");

    @JsonValue
    public final String value;

    private CreateFineTuneRequestModel2(String value) {
        this.value = value;
    }
}
