/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateImageRequest {
    /**
     * The number of images to generate. Must be between 1 and 10.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("n")
    public Long n;

    public CreateImageRequest withN(Long n) {
        this.n = n;
        return this;
    }
    
    /**
     * A text description of the desired image(s). The maximum length is 1000 characters.
     */
    @JsonProperty("prompt")
    public String prompt;

    public CreateImageRequest withPrompt(String prompt) {
        this.prompt = prompt;
        return this;
    }
    
    /**
     * The format in which the generated images are returned. Must be one of `url` or `b64_json`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_format")
    public CreateImageRequestResponseFormat responseFormat;

    public CreateImageRequest withResponseFormat(CreateImageRequestResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }
    
    /**
     * The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("size")
    public CreateImageRequestSize size;

    public CreateImageRequest withSize(CreateImageRequestSize size) {
        this.size = size;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("user")
    public Object user;

    public CreateImageRequest withUser(Object user) {
        this.user = user;
        return this;
    }
    
    public CreateImageRequest(@JsonProperty("prompt") String prompt) {
        this.prompt = prompt;
  }
}
