/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;



public class CreateEditResponseChoicesLogprobsTopLogprobs {
    public CreateEditResponseChoicesLogprobsTopLogprobs(){}
}
