/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import openai.javasdk.utils.SpeakeasyMetadata;


public class CreateImageVariationRequest2 {
    /**
     * The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square.
     */
    @SpeakeasyMetadata("multipartForm:file")
    public CreateImageVariationRequestImage image;

    public CreateImageVariationRequest2 withImage(CreateImageVariationRequestImage image) {
        this.image = image;
        return this;
    }
    
    /**
     * The number of images to generate. Must be between 1 and 10.
     */
    @SpeakeasyMetadata("multipartForm:name=n")
    public Long n;

    public CreateImageVariationRequest2 withN(Long n) {
        this.n = n;
        return this;
    }
    
    /**
     * The format in which the generated images are returned. Must be one of `url` or `b64_json`.
     */
    @SpeakeasyMetadata("multipartForm:name=response_format")
    public CreateImageVariationRequestResponseFormat responseFormat;

    public CreateImageVariationRequest2 withResponseFormat(CreateImageVariationRequestResponseFormat responseFormat) {
        this.responseFormat = responseFormat;
        return this;
    }
    
    /**
     * The size of the generated images. Must be one of `256x256`, `512x512`, or `1024x1024`.
     */
    @SpeakeasyMetadata("multipartForm:name=size")
    public CreateImageVariationRequestSize size;

    public CreateImageVariationRequest2 withSize(CreateImageVariationRequestSize size) {
        this.size = size;
        return this;
    }
    
    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).
     * 
     */
    @SpeakeasyMetadata("multipartForm:name=user")
    public String user;

    public CreateImageVariationRequest2 withUser(String user) {
        this.user = user;
        return this;
    }
    
    public CreateImageVariationRequest2(@JsonProperty("image") CreateImageVariationRequestImage image) {
        this.image = image;
  }
}
