/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FineTuneHyperparams - The hyperparameters used for the fine-tuning job. See the [Fine-tuning Guide](/docs/guides/fine-tuning/hyperparameters) for more details.
 */

public class FineTuneHyperparams {
    /**
     * The batch size to use for training. The batch size is the number of
     * training examples used to train a single forward and backward pass.
     * 
     */
    @JsonProperty("batch_size")
    public Long batchSize;

    public FineTuneHyperparams withBatchSize(Long batchSize) {
        this.batchSize = batchSize;
        return this;
    }
    
    /**
     * The number of classes to use for computing classification metrics.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("classification_n_classes")
    public Long classificationNClasses;

    public FineTuneHyperparams withClassificationNClasses(Long classificationNClasses) {
        this.classificationNClasses = classificationNClasses;
        return this;
    }
    
    /**
     * The positive class to use for computing classification metrics.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("classification_positive_class")
    public String classificationPositiveClass;

    public FineTuneHyperparams withClassificationPositiveClass(String classificationPositiveClass) {
        this.classificationPositiveClass = classificationPositiveClass;
        return this;
    }
    
    /**
     * The classification metrics to compute using the validation dataset at the end of every epoch.
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("compute_classification_metrics")
    public Boolean computeClassificationMetrics;

    public FineTuneHyperparams withComputeClassificationMetrics(Boolean computeClassificationMetrics) {
        this.computeClassificationMetrics = computeClassificationMetrics;
        return this;
    }
    
    /**
     * The learning rate multiplier to use for training.
     * 
     */
    @JsonProperty("learning_rate_multiplier")
    public Double learningRateMultiplier;

    public FineTuneHyperparams withLearningRateMultiplier(Double learningRateMultiplier) {
        this.learningRateMultiplier = learningRateMultiplier;
        return this;
    }
    
    /**
     * The number of epochs to train the model for. An epoch refers to one
     * full cycle through the training dataset.
     * 
     */
    @JsonProperty("n_epochs")
    public Long nEpochs;

    public FineTuneHyperparams withNEpochs(Long nEpochs) {
        this.nEpochs = nEpochs;
        return this;
    }
    
    /**
     * The weight to use for loss on the prompt tokens.
     * 
     */
    @JsonProperty("prompt_loss_weight")
    public Double promptLossWeight;

    public FineTuneHyperparams withPromptLossWeight(Double promptLossWeight) {
        this.promptLossWeight = promptLossWeight;
        return this;
    }
    
    public FineTuneHyperparams(@JsonProperty("batch_size") Long batchSize, @JsonProperty("learning_rate_multiplier") Double learningRateMultiplier, @JsonProperty("n_epochs") Long nEpochs, @JsonProperty("prompt_loss_weight") Double promptLossWeight) {
        this.batchSize = batchSize;
        this.learningRateMultiplier = learningRateMultiplier;
        this.nEpochs = nEpochs;
        this.promptLossWeight = promptLossWeight;
  }
}
