/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FineTune - The `FineTune` object represents a fine-tuning job that has been created through the API.
 * 
 */

public class FineTune {
    /**
     * The unix timestamp for when the fine-tuning job was created.
     */
    @JsonProperty("created_at")
    public Long createdAt;

    public FineTune withCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * The list of events that have been observed in the lifecycle of the FineTune job.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("events")
    public FineTuneEvent[] events;

    public FineTune withEvents(FineTuneEvent[] events) {
        this.events = events;
        return this;
    }
    
    /**
     * The name of the fine-tuned model that is being created.
     */
    @JsonProperty("fine_tuned_model")
    public String fineTunedModel;

    public FineTune withFineTunedModel(String fineTunedModel) {
        this.fineTunedModel = fineTunedModel;
        return this;
    }
    
    /**
     * The hyperparameters used for the fine-tuning job. See the [Fine-tuning Guide](/docs/guides/fine-tuning/hyperparameters) for more details.
     */
    @JsonProperty("hyperparams")
    public FineTuneHyperparams hyperparams;

    public FineTune withHyperparams(FineTuneHyperparams hyperparams) {
        this.hyperparams = hyperparams;
        return this;
    }
    
    /**
     * The object identifier, which can be referenced in the API endpoints.
     */
    @JsonProperty("id")
    public String id;

    public FineTune withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The base model that is being fine-tuned.
     */
    @JsonProperty("model")
    public String model;

    public FineTune withModel(String model) {
        this.model = model;
        return this;
    }
    
    /**
     * The object type, which is always "fine-tune".
     */
    @JsonProperty("object")
    public String object;

    public FineTune withObject(String object) {
        this.object = object;
        return this;
    }
    
    /**
     * The organization that owns the fine-tuning job.
     */
    @JsonProperty("organization_id")
    public String organizationId;

    public FineTune withOrganizationId(String organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    /**
     * The compiled results files for the fine-tuning job.
     */
    @JsonProperty("result_files")
    public OpenAIFile[] resultFiles;

    public FineTune withResultFiles(OpenAIFile[] resultFiles) {
        this.resultFiles = resultFiles;
        return this;
    }
    
    /**
     * The current status of the fine-tuning job, which can be either `created`, `pending`, `running`, `succeeded`, `failed`, or `cancelled`.
     */
    @JsonProperty("status")
    public String status;

    public FineTune withStatus(String status) {
        this.status = status;
        return this;
    }
    
    /**
     * The list of files used for training.
     */
    @JsonProperty("training_files")
    public OpenAIFile[] trainingFiles;

    public FineTune withTrainingFiles(OpenAIFile[] trainingFiles) {
        this.trainingFiles = trainingFiles;
        return this;
    }
    
    /**
     * The unix timestamp for when the fine-tuning job was last updated.
     */
    @JsonProperty("updated_at")
    public Long updatedAt;

    public FineTune withUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }
    
    /**
     * The list of files used for validation.
     */
    @JsonProperty("validation_files")
    public OpenAIFile[] validationFiles;

    public FineTune withValidationFiles(OpenAIFile[] validationFiles) {
        this.validationFiles = validationFiles;
        return this;
    }
    
    public FineTune(@JsonProperty("created_at") Long createdAt, @JsonProperty("fine_tuned_model") String fineTunedModel, @JsonProperty("hyperparams") FineTuneHyperparams hyperparams, @JsonProperty("id") String id, @JsonProperty("model") String model, @JsonProperty("object") String object, @JsonProperty("organization_id") String organizationId, @JsonProperty("result_files") OpenAIFile[] resultFiles, @JsonProperty("status") String status, @JsonProperty("training_files") OpenAIFile[] trainingFiles, @JsonProperty("updated_at") Long updatedAt, @JsonProperty("validation_files") OpenAIFile[] validationFiles) {
        this.createdAt = createdAt;
        this.fineTunedModel = fineTunedModel;
        this.hyperparams = hyperparams;
        this.id = id;
        this.model = model;
        this.object = object;
        this.organizationId = organizationId;
        this.resultFiles = resultFiles;
        this.status = status;
        this.trainingFiles = trainingFiles;
        this.updatedAt = updatedAt;
        this.validationFiles = validationFiles;
  }
}
