/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class FineTuneEvent {
    @JsonProperty("created_at")
    public Long createdAt;

    public FineTuneEvent withCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    @JsonProperty("level")
    public String level;

    public FineTuneEvent withLevel(String level) {
        this.level = level;
        return this;
    }
    
    @JsonProperty("message")
    public String message;

    public FineTuneEvent withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonProperty("object")
    public String object;

    public FineTuneEvent withObject(String object) {
        this.object = object;
        return this;
    }
    
    public FineTuneEvent(@JsonProperty("created_at") Long createdAt, @JsonProperty("level") String level, @JsonProperty("message") String message, @JsonProperty("object") String object) {
        this.createdAt = createdAt;
        this.level = level;
        this.message = message;
        this.object = object;
  }
}
