/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Image - Represents the url or the content of an image generated by the OpenAI API.
 */

public class Image {
    /**
     * The base64-encoded JSON of the generated image, if `response_format` is `b64_json`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("b64_json")
    public String b64Json;

    public Image withB64Json(String b64Json) {
        this.b64Json = b64Json;
        return this;
    }
    
    /**
     * The URL of the generated image, if `response_format` is `url` (default).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    public String url;

    public Image withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public Image(){}
}
