/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class ImagesResponseData {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("b64_json")
    public String b64Json;
    public ImagesResponseData withB64Json(String b64Json) {
        this.b64Json = b64Json;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    public String url;
    public ImagesResponseData withUrl(String url) {
        this.url = url;
        return this;
    }
    

    public ImagesResponseData(){}
}
