/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ImagesResponse - OK
 */
public class ImagesResponse {
    @JsonProperty("created")
    public Long created;

    public ImagesResponse withCreated(Long created) {
        this.created = created;
        return this;
    }
    
    @JsonProperty("data")
    public ImagesResponseData[] data;

    public ImagesResponse withData(ImagesResponseData[] data) {
        this.data = data;
        return this;
    }
    
    public ImagesResponse(@JsonProperty("created") Long created, @JsonProperty("data") ImagesResponseData[] data) {
        this.created = created;
        this.data = data;
  }
}
