/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package openai.javasdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OpenAIFile - OK
 */

public class OpenAIFile {
    @JsonProperty("bytes")
    public Long bytes;

    public OpenAIFile withBytes(Long bytes) {
        this.bytes = bytes;
        return this;
    }
    
    @JsonProperty("created_at")
    public Long createdAt;

    public OpenAIFile withCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    @JsonProperty("filename")
    public String filename;

    public OpenAIFile withFilename(String filename) {
        this.filename = filename;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public OpenAIFile withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("object")
    public String object;

    public OpenAIFile withObject(String object) {
        this.object = object;
        return this;
    }
    
    @JsonProperty("purpose")
    public String purpose;

    public OpenAIFile withPurpose(String purpose) {
        this.purpose = purpose;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public String status;

    public OpenAIFile withStatus(String status) {
        this.status = status;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status_details")
    public OpenAIFileStatusDetails statusDetails;

    public OpenAIFile withStatusDetails(OpenAIFileStatusDetails statusDetails) {
        this.statusDetails = statusDetails;
        return this;
    }
    
    public OpenAIFile(@JsonProperty("bytes") Long bytes, @JsonProperty("created_at") Long createdAt, @JsonProperty("filename") String filename, @JsonProperty("id") String id, @JsonProperty("object") String object, @JsonProperty("purpose") String purpose) {
        this.bytes = bytes;
        this.createdAt = createdAt;
        this.filename = filename;
        this.id = id;
        this.object = object;
        this.purpose = purpose;
  }
}
